server:
  port: 8085
  servlet:
    contextPath: /
spring:
  datasource:
    password: mabrouk12
    username: root
    url: jdbc:mysql://localhost:3306/ebanking  # MySQL URL
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL Dialect
        types.print.banner: false
        format_sql: true
